name: Continuous Integration
on: [ pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEMO_NAVITIA_TOKEN: ${{ secrets.DEMO_NAVITIA_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.8.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Test & Build
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build
      - name: Publish test reports
        uses: actions/upload-artifact@v3.1.1
        if: always()
        with:
          name: Test results
          path: '**/build/test-results/test/TEST-*.xml'
